### ISSUE TITLE
Callback Function on ContextMenu close?

### ISSUE THREAD

**Issue by timhilgenstoehler** [mpiannucci/react-native-uimenu#1]
Hey,

thank you very much for this repo. I got the ContextMenu working very well! Is there a possibility to call a function when the user clicks outside (on the blurred content) to close the contextMenu View?

Kind Regards,
Tim

**Comment by mpiannucci** [comment]
Yeah you just have to add a new prop for the callback and implement this delegate method in `ContextMenuView.m`

https://developer.apple.com/documentation/uikit/uicontextmenuinteractiondelegate/3375806-contextmenuinteraction

I will update this repo soon with that functionality

**Comment by timhilgenstoehler** [comment]
Hey, cool that would be awesome! I am not so familiar with C and still learning the native module bridges, so I am looking forward to your solution :) Thanks!

**Comment by mpiannucci** [comment]
I added `onCancel` functionality. It only gets fired when the user does not select an option and the user taps outside of the menu

**Comment by timhilgenstoehler** [comment]
Thanks a lot, it is working perfectly and it helped to understand the React Native Bridge :)

**Comment by mpiannucci** [comment]
Awesome glad to help!
